Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,7 +15,7 @@ on:
         required: true
         default: 'v5.12.0-m6'
       send-notification:
-        description: 'send google chat notification'
+        description: 'send email notification'
         required: true
         default: true
 
@@ -83,7 +83,27 @@ jobs:
         sudo -E python3 ../product-is/oidc-conformance-tests/start_conformance_suite.py $DOCKER_COMPOSE_FILE
         
     - name: Run Tests
-      run: sudo bash ./product-is/oidc-conformance-tests/test_runner.sh 
+      run: sudo bash ./product-is/oidc-conformance-tests/test_runner.sh
+      
+    - name: Test Results
+      run: |
+        IS_SUCCESSFUL=false
+        if sudo python3 ./product-is/oidc-conformance-tests/export_results.py https://localhost:8443
+        then
+          IS_SUCCESSFUL=true
+        fi
+        if $IS_SUCCESSFUL
+        then
+          echo "======================"
+          echo "All Test Cases Passed!
+          echo "======================"
+          exit 0
+        else      
+          echo "============================================="
+          echo "Failed Test Cases Found. Exiting with Failure"
+          echo "============================================="
+          exit 1
+        fi
       
     - name: Archive test results
       uses: actions/upload-artifact@v2
@@ -112,11 +132,11 @@ jobs:
           sudo python3 ./product-is/oidc-conformance-tests/send_notification.py $CONFORMANCE_SUITE_URL $GITHUB_RUN_NUMBER ${{job.status}} ${{github.repository}} ${{github.run_id}} ${{secrets.SENDER_EMAIL}} ${{secrets.PASSWORD}} ${{secrets.RECEIVER_LIST}}
         elif [ $SEND_NOTIFICATION == "FALSE" ]; then
           echo "========================================"
-          echo "Skipped sending google chat notification"
+          echo "Skipped Sending Email Notification"
           echo "========================================"
         else
           echo "================================================================="
-          echo "Invalid parameter value. Skipped sending google chat notification"
+          echo "Invalid parameter value. Skipped sending email notification"
           echo "================================================================="
         fi
        
